# fly.toml app configuration file generated for 1d2h-still-breeze-5014 on 2025-11-03T12:55:39+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '1d2h-still-breeze-5014'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8079
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  mermory = 256